# Generated by Django 5.0.2 on 2024-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_respuesta_fecha_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='adjunto1',
            field=models.ImageField(blank=True, null=True, upload_to='adjuntos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='adjunto2',
            field=models.ImageField(blank=True, null=True, upload_to='adjuntos/'),
        ),
    ]
