# Generated by Django 5.0.2 on 2024-03-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_ticket_adjunto1_ticket_adjunto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='adjunto1',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='adjunto2',
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo1', models.BinaryField(blank=True, null=True)),
                ('archivo2', models.BinaryField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ticket')),
            ],
        ),
    ]
